export const homeData = [
  {
    title: 'Building the YouTube UI with Ionic',
    videoId: 'VIDEO_ID_1',
    thumbnail: 'https://img.youtube.com/vi/VIDEO_ID_1/default.jpg',
    description: 'Mô tả video 1',
    views: 1000,
    likes: 50,
    dislikes: 2,
    publishDate: '2022-01-01',
  },
  {
    title: 'Video 2',
    videoId: 'VIDEO_ID_2',
    thumbnail: 'https://img.youtube.com/vi/VIDEO_ID_2/default.jpg',
    description: 'Mô tả video 2',
    views: 500,
    likes: 30,
    dislikes: 1,
    publishDate: '2022-02-15',
  },
  {
    title: 'Video 3',
    videoId: 'VIDEO_ID_3',
    thumbnail: 'https://img.youtube.com/vi/VIDEO_ID_3/default.jpg',
    description: 'Mô tả video 3',
    views: 1200,
    likes: 60,
    dislikes: 3,
    publishDate: '2022-03-20',
  },
  {
    title: 'Video 4',
    videoId: 'VIDEO_ID_4',
    thumbnail: 'https://img.youtube.com/vi/VIDEO_ID_4/default.jpg',
    description: 'Mô tả video 4',
    views: 800,
    likes: 40,
    dislikes: 2,
    publishDate: '2022-04-10',
  },
  {
    title: 'Video 5',
    videoId: 'VIDEO_ID_5',
    thumbnail: 'https://img.youtube.com/vi/VIDEO_ID_5/default.jpg',
    description: 'Mô tả video 5',
    views: 1500,
    likes: 70,
    dislikes: 4,
    publishDate: '2022-05-05',
  },
  {
    title: 'Video 6',
    videoId: 'VIDEO_ID_6',
    thumbnail: 'https://img.youtube.com/vi/VIDEO_ID_6/default.jpg',
    description: 'Mô tả video 6',
    views: 600,
    likes: 25,
    dislikes: 1,
    publishDate: '2022-06-15',
  },
  {
    title: 'Video 7',
    videoId: 'VIDEO_ID_7',
    thumbnail: 'https://img.youtube.com/vi/VIDEO_ID_7/default.jpg',
    description: 'Mô tả video 7',
    views: 2000,
    likes: 100,
    dislikes: 5,
    publishDate: '2022-07-02',
  },
  {
    title: 'Video 8',
    videoId: 'VIDEO_ID_8',
    thumbnail: 'https://img.youtube.com/vi/VIDEO_ID_8/default.jpg',
    description: 'Mô tả video 8',
    views: 700,
    likes: 35,
    dislikes: 2,
    publishDate: '2022-08-10',
  },
  {
    title: 'Video 9',
    videoId: 'VIDEO_ID_9',
    thumbnail: 'https://img.youtube.com/vi/VIDEO_ID_9/default.jpg',
    description: 'Mô tả video 9',
    views: 900,
    likes: 45,
    dislikes: 3,
    publishDate: '2022-09-20',
  },
  {
    title: 'Video 10',
    videoId: 'VIDEO_ID_10',
    thumbnail: 'https://img.youtube.com/vi/VIDEO_ID_10/default.jpg',
    description: 'Mô tả video 10',
    views: 1100,
    likes: 55,
    dislikes: 4,
    publishDate: '2022-10-05',
  },
];
